# Generated by Django 5.2.1 on 2025-08-30 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=200, verbose_name='Hero title')),
                ('hero_title_kk', models.CharField(max_length=200, null=True, verbose_name='Hero title')),
                ('hero_title_ru', models.CharField(max_length=200, null=True, verbose_name='Hero title')),
                ('hero_title_en', models.CharField(max_length=200, null=True, verbose_name='Hero title')),
                ('hero_subtitle', models.CharField(blank=True, max_length=300, verbose_name='Hero subtitle')),
                ('hero_subtitle_kk', models.CharField(blank=True, max_length=300, null=True, verbose_name='Hero subtitle')),
                ('hero_subtitle_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Hero subtitle')),
                ('hero_subtitle_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Hero subtitle')),
                ('cta_label', models.CharField(blank=True, max_length=100, verbose_name='CTA label')),
                ('cta_label_kk', models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA label')),
                ('cta_label_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA label')),
                ('cta_label_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA label')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta title')),
                ('meta_title_kk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('meta_description_kk', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('meta_description_ru', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='Meta description')),
            ],
            options={
                'verbose_name': 'Home page',
                'verbose_name_plural': 'Home pages',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_kk', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('body', models.TextField(blank=True, verbose_name='Body')),
                ('body_kk', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('body_ru', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('body_en', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('order', models.PositiveIntegerField(default=0)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='contents.homepage')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['order', 'id'],
            },
        ),
    ]
