# Generated by Django 5.2.1 on 2025-08-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_benefit_delete_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='cta_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='benefit',
            name='cta_label_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='benefit',
            name='cta_label_kk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='benefit',
            name='cta_label_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
