# Generated by Django 5.2.1 on 2025-08-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_benefit_cta_label_benefit_cta_label_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=200, verbose_name='Services title')),
                ('hero_subtitle', models.CharField(blank=True, max_length=300, verbose_name='Services subtitle')),
                ('cta_label', models.CharField(blank=True, max_length=100, verbose_name='CTA label')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
            ],
            options={
                'verbose_name': 'Services page',
                'verbose_name_plural': 'Services pages',
            },
        ),
    ]
