# Generated by Django 5.2.1 on 2025-08-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_servicespage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='cta_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA label'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='cta_label_kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA label'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='cta_label_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA label'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='hero_subtitle_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Services subtitle'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='hero_subtitle_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Services subtitle'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='hero_subtitle_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Services subtitle'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='hero_title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Services title'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='hero_title_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Services title'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='hero_title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Services title'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='meta_description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='meta_title_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title'),
        ),
    ]
