# Generated by Django 5.2.1 on 2025-08-30 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_servicespage_cta_label_en_servicespage_cta_label_kk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('title_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('body', models.TextField(blank=True, verbose_name='Body')),
                ('body_kk', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('body_ru', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('body_en', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('cta_label', models.CharField(blank=True, max_length=100, verbose_name='CTA label')),
                ('cta_label_kk', models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA label')),
                ('cta_label_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA label')),
                ('cta_label_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA label')),
                ('cta_url', models.URLField(blank=True, verbose_name='CTA URL')),
                ('order', models.PositiveIntegerField(default=0)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_sections', to='contents.homepage')),
            ],
            options={
                'verbose_name': 'Benefit section',
                'verbose_name_plural': 'Benefit sections',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BenefitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='Label')),
                ('label_kk', models.CharField(max_length=120, null=True, verbose_name='Label')),
                ('label_ru', models.CharField(max_length=120, null=True, verbose_name='Label')),
                ('label_en', models.CharField(max_length=120, null=True, verbose_name='Label')),
                ('detail', models.CharField(blank=True, max_length=200, verbose_name='Detail')),
                ('detail_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Detail')),
                ('detail_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Detail')),
                ('detail_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Detail')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contents.benefitsection')),
            ],
            options={
                'verbose_name': 'Benefit item',
                'verbose_name_plural': 'Benefit items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='Benefit',
        ),
    ]
