# Generated by Django 5.2.1 on 2025-08-30 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_benefitsection_benefititem_delete_benefit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefititem',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='benefitsection',
            name='cta_label',
        ),
        migrations.RemoveField(
            model_name='benefitsection',
            name='cta_label_en',
        ),
        migrations.RemoveField(
            model_name='benefitsection',
            name='cta_label_kk',
        ),
        migrations.RemoveField(
            model_name='benefitsection',
            name='cta_label_ru',
        ),
        migrations.RemoveField(
            model_name='benefitsection',
            name='cta_url',
        ),
    ]
