# Generated by Django 5.2.1 on 2025-08-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_aboutpage_delete_servicespage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='body_en',
            field=models.TextField(blank=True, null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='body_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='body_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_title_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='title_kk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='benefitsection',
            name='cta_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA label'),
        ),
        migrations.AddField(
            model_name='benefitsection',
            name='cta_label_kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA label'),
        ),
        migrations.AddField(
            model_name='benefitsection',
            name='cta_label_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA label'),
        ),
    ]
