# Generated by Django 5.2.1 on 2025-08-30 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_aboutpage_body_en_aboutpage_body_kk_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('title_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Services block',
                'verbose_name_plural': 'Services blocks',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Name')),
                ('name_kk', models.CharField(max_length=160, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=160, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=160, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Item description')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='Item description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Item description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Item description')),
                ('icon_svg', models.TextField(blank=True, verbose_name='Inline SVG')),
                ('tags_text', models.CharField(blank=True, help_text='Example: Open category, <250g, A1/A3', max_length=300, verbose_name='Visual tags (comma-separated)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contents.servicesblock')),
            ],
            options={
                'verbose_name': 'Service item',
                'verbose_name_plural': 'Service items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicesBlockPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_object_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='contents.servicesblock')),
                ('page_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Services block placement',
                'verbose_name_plural': 'Services block placements',
                'ordering': ['order', 'id'],
                'unique_together': {('block', 'page_content_type', 'page_object_id')},
            },
        ),
    ]
