# Generated by Django 5.2.1 on 2025-08-31 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_servicesblock_serviceitem_servicesblockplacement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefitsection',
            name='body',
        ),
        migrations.RemoveField(
            model_name='benefitsection',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='benefitsection',
            name='body_kk',
        ),
        migrations.RemoveField(
            model_name='benefitsection',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='benefitsection',
            name='cta_label',
        ),
        migrations.RemoveField(
            model_name='benefitsection',
            name='cta_label_en',
        ),
        migrations.RemoveField(
            model_name='benefitsection',
            name='cta_label_kk',
        ),
        migrations.RemoveField(
            model_name='benefitsection',
            name='cta_label_ru',
        ),
        migrations.RemoveField(
            model_name='benefitsection',
            name='cta_url',
        ),
    ]
