# Generated by Django 5.2.1 on 2025-08-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_remove_benefitsection_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefititem',
            name='label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='benefititem',
            name='label_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='benefititem',
            name='label_kk',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='benefititem',
            name='label_ru',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Label'),
        ),
    ]
