# Generated by Django 5.2.1 on 2025-08-31 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0012_alter_benefititem_label_alter_benefititem_label_en_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('title_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team block',
                'verbose_name_plural': 'Team blocks',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Name')),
                ('name_kk', models.CharField(max_length=160, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=160, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=160, null=True, verbose_name='Name')),
                ('post', models.CharField(blank=True, max_length=160, verbose_name='Position')),
                ('post_kk', models.CharField(blank=True, max_length=160, null=True, verbose_name='Position')),
                ('post_ru', models.CharField(blank=True, max_length=160, null=True, verbose_name='Position')),
                ('post_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='Position')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('photo_url', models.CharField(blank=True, max_length=500, verbose_name='Photo URL or static path')),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='contents.teamblock')),
            ],
            options={
                'verbose_name': 'Team member',
                'verbose_name_plural': 'Team members',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamBlockPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_object_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='contents.teamblock')),
                ('page_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Team block placement',
                'verbose_name_plural': 'Team block placements',
                'ordering': ['order', 'id'],
                'unique_together': {('block', 'page_content_type', 'page_object_id')},
            },
        ),
    ]
