# Generated by Django 5.2.1 on 2025-08-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_teamblock_teammember_teamblockplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo_url',
            field=models.ImageField(upload_to='teams/'),
        ),
    ]
