# Generated by Django 5.2.1 on 2025-08-31 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0014_alter_teammember_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamblock',
            name='description',
        ),
        migrations.RemoveField(
            model_name='teamblock',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='teamblock',
            name='description_kk',
        ),
        migrations.RemoveField(
            model_name='teamblock',
            name='description_ru',
        ),
    ]
