# Generated by Django 5.2.1 on 2025-08-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0015_remove_teamblock_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, upload_to='team/', verbose_name='Photo'),
        ),
    ]
