# Generated by Django 5.2.1 on 2025-08-31 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0016_remove_teammember_photo_url_teammember_photo'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('title_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partners block',
                'verbose_name_plural': 'Partners blocks',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_code', models.TextField(verbose_name='Inline SVG')),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='contents.partnersblock')),
            ],
            options={
                'verbose_name': 'Partner logo',
                'verbose_name_plural': 'Partner logos',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PartnersBlockPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_object_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='contents.partnersblock')),
                ('page_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Partners block placement',
                'verbose_name_plural': 'Partners block placements',
                'ordering': ['order', 'id'],
                'unique_together': {('block', 'page_content_type', 'page_object_id')},
            },
        ),
    ]
