# Generated by Django 5.2.1 on 2025-09-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0017_partnersblock_partnerlogo_partnersblockplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='mission_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Mission text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_text_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Mission text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_text_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Mission text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_text_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Mission text'),
        ),
        migrations.AlterField(
            model_name='partnersblock',
            name='slug',
            field=models.SlugField(default='partners-core', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='servicesblock',
            name='slug',
            field=models.SlugField(default='categories', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='teamblock',
            name='slug',
            field=models.SlugField(default='team-core', unique=True, verbose_name='Slug'),
        ),
    ]
