# Generated by Django 5.2.1 on 2025-09-01 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0018_homepage_mission_text_homepage_mission_text_en_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('title_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery block',
                'verbose_name_plural': 'Gallery blocks',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Image')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Alt text')),
                ('alt_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt text')),
                ('alt_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt text')),
                ('alt_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt text')),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contents.galleryblock')),
            ],
            options={
                'verbose_name': 'Gallery item',
                'verbose_name_plural': 'Gallery items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryBlockPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_object_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='contents.galleryblock')),
                ('page_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Gallery block placement',
                'verbose_name_plural': 'Gallery block placements',
                'ordering': ['order', 'id'],
                'unique_together': {('block', 'page_content_type', 'page_object_id')},
            },
        ),
    ]
