# Generated by Django 5.2.1 on 2025-09-01 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0019_galleryblock_galleryitem_galleryblockplacement'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinksBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('title_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social links block',
                'verbose_name_plural': 'Social links blocks',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='galleryblock',
            name='slug',
            field=models.SlugField(default='core-gallery', unique=True, verbose_name='Slug'),
        ),
        migrations.CreateModel(
            name='SocialLinkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='Accessible label / tooltip')),
                ('label_kk', models.CharField(blank=True, max_length=120, null=True, verbose_name='Accessible label / tooltip')),
                ('label_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Accessible label / tooltip')),
                ('label_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Accessible label / tooltip')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('svg_code', models.TextField(verbose_name='Inline SVG')),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contents.sociallinksblock')),
            ],
            options={
                'verbose_name': 'Social link',
                'verbose_name_plural': 'Social links',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLinksBlockPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_object_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='contents.sociallinksblock')),
                ('page_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Social links block placement',
                'verbose_name_plural': 'Social links block placements',
                'ordering': ['order', 'id'],
                'unique_together': {('block', 'page_content_type', 'page_object_id')},
            },
        ),
    ]
