# Generated by Django 5.2.1 on 2025-09-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0021_menu_alter_sociallinksblock_slug_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='body_kk',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='body_ru',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='CTA label'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA label'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_label_kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA label'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_label_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA label'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Mission text'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_text_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Mission text'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_text_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Mission text'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_text_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Mission text'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='subtitle',
            field=models.TextField(blank=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='subtitle_en',
            field=models.TextField(blank=True, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='subtitle_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='subtitle_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Subtitle'),
        ),
    ]
