# Generated by Django 5.2.1 on 2025-09-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0022_remove_aboutpage_body_remove_aboutpage_body_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='image',
            field=models.ImageField(blank=True, upload_to='about/', verbose_name='Image'),
        ),
    ]
