# Generated by Django 5.2.1 on 2025-09-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0023_aboutpage_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='benefitsection',
            name='benefitsection_exactly_one_parent',
        ),
        migrations.RemoveField(
            model_name='benefitsection',
            name='aboutpage',
        ),
        migrations.RemoveField(
            model_name='benefitsection',
            name='homepage',
        ),
        migrations.AddField(
            model_name='benefitsection',
            name='slug',
            field=models.SlugField(blank=True, help_text='Уникальный идентификатор секции для шаблона', verbose_name='Slug'),
        ),
    ]
