# Generated by Django 5.2.1 on 2025-09-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0025_servicepage_servicebutton_servicebenefit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprogramitem',
            name='image1',
            field=models.ImageField(blank=True, upload_to='program/', verbose_name='Image1'),
        ),
        migrations.AddField(
            model_name='serviceprogramitem',
            name='image2',
            field=models.ImageField(blank=True, upload_to='program/', verbose_name='Image2'),
        ),
        migrations.AddField(
            model_name='serviceprogramitem',
            name='image3',
            field=models.ImageField(blank=True, upload_to='program/', verbose_name='Image3'),
        ),
    ]
