# Generated by Django 5.2.1 on 2025-09-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0026_serviceprogramitem_image1_serviceprogramitem_image2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceProgramImage',
        ),
    ]
