# Generated by Django 5.2.1 on 2025-09-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0027_delete_serviceprogramimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='program_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Program title'),
        ),
    ]
