# Generated by Django 5.2.1 on 2025-09-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0028_servicepage_program_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='program_title_en',
            field=models.CharField(blank=True, default='Program', max_length=200, null=True, verbose_name='Program title'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='program_title_kk',
            field=models.CharField(blank=True, default='Program', max_length=200, null=True, verbose_name='Program title'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='program_title_ru',
            field=models.CharField(blank=True, default='Program', max_length=200, null=True, verbose_name='Program title'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='program_title',
            field=models.CharField(blank=True, default='Program', max_length=200, verbose_name='Program title'),
        ),
    ]
