# Generated by Django 5.2.1 on 2025-09-01 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0029_servicepage_program_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='fleet-core', unique=True, verbose_name='Slug')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Title')),
                ('title_kk', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Title')),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fleet block',
                'verbose_name_plural': 'Fleet blocks',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FleetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_kk', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('subtitle', models.CharField(blank=True, default='', max_length=300, verbose_name='Subtitle')),
                ('subtitle_kk', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Subtitle')),
                ('subtitle_ru', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Subtitle')),
                ('subtitle_en', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Subtitle')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('description_kk', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, upload_to='fleet/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contents.fleetblock')),
            ],
            options={
                'verbose_name': 'Fleet item',
                'verbose_name_plural': 'Fleet items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FleetSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160, verbose_name='Key')),
                ('key_kk', models.CharField(max_length=160, null=True, verbose_name='Key')),
                ('key_ru', models.CharField(max_length=160, null=True, verbose_name='Key')),
                ('key_en', models.CharField(max_length=160, null=True, verbose_name='Key')),
                ('value', models.CharField(blank=True, default='', max_length=200, verbose_name='Value')),
                ('value_kk', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Value')),
                ('value_ru', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Value')),
                ('value_en', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Value')),
                ('order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='contents.fleetitem')),
            ],
            options={
                'verbose_name': 'Fleet spec',
                'verbose_name_plural': 'Fleet specs',
                'ordering': ['order', 'id'],
            },
        ),
    ]
