# Generated by Django 5.2.1 on 2025-09-01 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0030_fleetblock_fleetitem_fleetspec'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='faq-core', unique=True, verbose_name='Slug')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('title_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ block',
                'verbose_name_plural': 'FAQ blocks',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
                ('question_kk', models.CharField(max_length=300, null=True, verbose_name='Question')),
                ('question_ru', models.CharField(max_length=300, null=True, verbose_name='Question')),
                ('question_en', models.CharField(max_length=300, null=True, verbose_name='Question')),
                ('answer', models.TextField(blank=True, verbose_name='Answer')),
                ('answer_kk', models.TextField(blank=True, null=True, verbose_name='Answer')),
                ('answer_ru', models.TextField(blank=True, null=True, verbose_name='Answer')),
                ('answer_en', models.TextField(blank=True, null=True, verbose_name='Answer')),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contents.faqblock')),
            ],
            options={
                'verbose_name': 'FAQ item',
                'verbose_name_plural': 'FAQ items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
