# Generated by Django 5.2.1 on 2025-09-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0031_faqblock_faqitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='cta_button_url',
        ),
    ]
