# Generated by Django 5.2.1 on 2025-09-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0032_remove_servicepage_cta_button_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqblock',
            name='cta_faq',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cta faq'),
        ),
    ]
