# Generated by Django 5.2.1 on 2025-09-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0033_faqblock_cta_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqblock',
            name='cta_faq_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cta faq'),
        ),
        migrations.AddField(
            model_name='faqblock',
            name='cta_faq_kk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cta faq'),
        ),
        migrations.AddField(
            model_name='faqblock',
            name='cta_faq_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cta faq'),
        ),
    ]
