# Generated by Django 5.2.1 on 2025-09-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0034_faqblock_cta_faq_en_faqblock_cta_faq_kk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepage',
            options={'ordering': ['services_order', 'id'], 'verbose_name': 'Service page', 'verbose_name_plural': 'Service pages'},
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='cta_label',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='cta_label_en',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='cta_label_kk',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='cta_label_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_label_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_label_kk',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_label_ru',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='cta_button_label',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='cta_button_label_en',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='cta_button_label_kk',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='cta_button_label_ru',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='cta_subtitle',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='cta_subtitle_en',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='cta_subtitle_kk',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='cta_subtitle_ru',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='cta_title',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='cta_title_en',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='cta_title_kk',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='cta_title_ru',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='card_icon_svg',
            field=models.TextField(blank=True, verbose_name='Card icon SVG'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='card_tags_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Card tags (comma-separated)'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Public'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='services_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='show_in_services_block',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Show in Services block'),
        ),
    ]
