# Generated by Django 5.2.1 on 2025-09-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0036_drop_old_services_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='show_in_services_block',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='show',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Show in cards'),
        ),
    ]
