# Generated by Django 5.2.1 on 2025-09-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0037_remove_servicepage_is_public_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceButton',
        ),
    ]
