# Generated by Django 5.2.1 on 2025-09-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0038_delete_servicebutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='card_description_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Card description (comma-separated)'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='card_description_text_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Card description (comma-separated)'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='card_description_text_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Card description (comma-separated)'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='card_description_text_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Card description (comma-separated)'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='card_tags_text_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Card tags (comma-separated)'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='card_tags_text_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Card tags (comma-separated)'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='card_tags_text_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Card tags (comma-separated)'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='card_title_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Card title (comma-separated)'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='card_title_text_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Card title (comma-separated)'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='card_title_text_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Card title (comma-separated)'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='card_title_text_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Card title (comma-separated)'),
        ),
    ]
