# Generated by Django 5.2.1 on 2025-09-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0040_alter_servicepage_card_description_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='subtitle',
            field=models.TextField(blank=True, verbose_name='УТП'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='subtitle_en',
            field=models.TextField(blank=True, null=True, verbose_name='УТП'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='subtitle_kk',
            field=models.TextField(blank=True, null=True, verbose_name='УТП'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='subtitle_ru',
            field=models.TextField(blank=True, null=True, verbose_name='УТП'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Офер'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Офер'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='title_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Офер'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Офер'),
        ),
    ]
