# Generated by Django 5.2.1 on 2025-09-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0041_alter_servicepage_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='education_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Education title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='education_title_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Education title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='education_title_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Education title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='education_title_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Education title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='education_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Education title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='education_title_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Education title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='education_title_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Education title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='education_title_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Education title'),
        ),
    ]
