# Generated by Django 5.2.1 on 2025-09-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0042_aboutpage_education_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='cta_descr',
            field=models.CharField(blank=True, max_length=300, verbose_name='CTA descr'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='cta_descr_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='CTA descr'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='cta_descr_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='CTA descr'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='cta_descr_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='CTA descr'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='cta_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='CTA title'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='cta_title_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='CTA title'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='cta_title_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='CTA title'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='cta_title_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='CTA title'),
        ),
    ]
