# Generated by Django 5.2.1 on 2025-09-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0043_servicepage_cta_descr_servicepage_cta_descr_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetblock',
            name='character_label',
            field=models.CharField(blank=True, default='Характеристики', max_length=100, verbose_name='Character Label'),
        ),
        migrations.AddField(
            model_name='fleetblock',
            name='character_label_en',
            field=models.CharField(blank=True, default='Характеристики', max_length=100, null=True, verbose_name='Character Label'),
        ),
        migrations.AddField(
            model_name='fleetblock',
            name='character_label_kk',
            field=models.CharField(blank=True, default='Характеристики', max_length=100, null=True, verbose_name='Character Label'),
        ),
        migrations.AddField(
            model_name='fleetblock',
            name='character_label_ru',
            field=models.CharField(blank=True, default='Характеристики', max_length=100, null=True, verbose_name='Character Label'),
        ),
    ]
