# Generated by Django 5.2.1 on 2025-09-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0044_fleetblock_character_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('title_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('subtitle', models.TextField(blank=True, verbose_name='Subtitle')),
                ('subtitle_kk', models.TextField(blank=True, null=True, verbose_name='Subtitle')),
                ('subtitle_ru', models.TextField(blank=True, null=True, verbose_name='Subtitle')),
                ('subtitle_en', models.TextField(blank=True, null=True, verbose_name='Subtitle')),
                ('phone_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Phone label')),
                ('phone_label_kk', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Phone label')),
                ('phone_label_ru', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Phone label')),
                ('phone_label_en', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Phone label')),
                ('phone_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Phone number')),
                ('email_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Email label')),
                ('email_label_kk', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Email label')),
                ('email_label_ru', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Email label')),
                ('email_label_en', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Email label')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Address label')),
                ('address_label_kk', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Address label')),
                ('address_label_ru', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Address label')),
                ('address_label_en', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Address label')),
                ('address_text', models.CharField(blank=True, default='', max_length=300, verbose_name='Address text')),
                ('address_text_kk', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Address text')),
                ('address_text_ru', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Address text')),
                ('address_text_en', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Address text')),
                ('address_url', models.URLField(blank=True, max_length=500, verbose_name='Address URL (map)')),
                ('footer_text', models.TextField(blank=True, default='', verbose_name='Footer text')),
                ('footer_text_kk', models.TextField(blank=True, default='', null=True, verbose_name='Footer text')),
                ('footer_text_ru', models.TextField(blank=True, default='', null=True, verbose_name='Footer text')),
                ('footer_text_en', models.TextField(blank=True, default='', null=True, verbose_name='Footer text')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta title')),
                ('meta_title_kk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('meta_description_kk', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('meta_description_ru', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact page',
                'verbose_name_plural': 'Contact pages',
            },
        ),
    ]
