# Generated by Django 5.2.1 on 2025-09-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0045_contactpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='image',
        ),
    ]
