# Generated by Django 5.2.1 on 2025-09-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0046_remove_aboutpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprogramitem',
            name='time_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Duration / time'),
        ),
        migrations.AddField(
            model_name='serviceprogramitem',
            name='time_kk',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Duration / time'),
        ),
        migrations.AddField(
            model_name='serviceprogramitem',
            name='time_ru',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Duration / time'),
        ),
    ]
