# Generated by Django 5.2.1 on 2025-09-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0047_serviceprogramitem_time_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='program_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Program title'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='program_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Program title'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='program_title_kk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Program title'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='program_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Program title'),
        ),
    ]
