# Generated by Django 5.2.1 on 2025-09-01 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('label', models.CharField(max_length=200, verbose_name='Button label')),
                ('label_kk', models.CharField(max_length=200, null=True, verbose_name='Button label')),
                ('label_ru', models.CharField(max_length=200, null=True, verbose_name='Button label')),
                ('label_en', models.CharField(max_length=200, null=True, verbose_name='Button label')),
                ('modal_title', models.CharField(blank=True, max_length=200, verbose_name='Modal title')),
                ('modal_title_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Modal title')),
                ('modal_title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Modal title')),
                ('modal_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Modal title')),
                ('submit_label', models.CharField(blank=True, max_length=200, verbose_name='Submit button label')),
                ('submit_label_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Submit button label')),
                ('submit_label_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Submit button label')),
                ('submit_label_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Submit button label')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feedback action',
                'verbose_name_plural': 'Feedback actions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('phone', models.CharField(max_length=64, verbose_name='Phone')),
                ('page_path', models.CharField(blank=True, max_length=500, verbose_name='Page path')),
                ('locale', models.CharField(blank=True, max_length=8, verbose_name='Locale')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='feedback.feedbackaction', verbose_name='Action')),
            ],
            options={
                'verbose_name': 'Feedback request',
                'verbose_name_plural': 'Feedback requests',
                'ordering': ['-created'],
            },
        ),
    ]
