# Generated by Django 5.2.1 on 2025-09-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackaction',
            name='name_label',
            field=models.CharField(blank=True, default='Имя', max_length=120, verbose_name='Name label'),
        ),
        migrations.AddField(
            model_name='feedbackaction',
            name='phone_label',
            field=models.CharField(blank=True, default='Телефон', max_length=120, verbose_name='Phone label'),
        ),
    ]
