# Generated by Django 5.2.1 on 2025-09-01 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedbackaction_name_label_feedbackaction_phone_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackaction',
            options={'verbose_name': 'Feedback action', 'verbose_name_plural': 'Feedback actions'},
        ),
        migrations.RemoveField(
            model_name='feedbackaction',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='feedbackaction',
            name='order',
        ),
        migrations.AddField(
            model_name='feedbackaction',
            name='name_label_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name label'),
        ),
        migrations.AddField(
            model_name='feedbackaction',
            name='name_label_kk',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name label'),
        ),
        migrations.AddField(
            model_name='feedbackaction',
            name='name_label_ru',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name label'),
        ),
        migrations.AddField(
            model_name='feedbackaction',
            name='phone_label_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Phone label'),
        ),
        migrations.AddField(
            model_name='feedbackaction',
            name='phone_label_kk',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Phone label'),
        ),
        migrations.AddField(
            model_name='feedbackaction',
            name='phone_label_ru',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Phone label'),
        ),
        migrations.AddField(
            model_name='feedbackaction',
            name='success_message',
            field=models.CharField(blank=True, max_length=200, verbose_name='Success message'),
        ),
        migrations.AddField(
            model_name='feedbackaction',
            name='success_message_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Success message'),
        ),
        migrations.AddField(
            model_name='feedbackaction',
            name='success_message_kk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Success message'),
        ),
        migrations.AddField(
            model_name='feedbackaction',
            name='success_message_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Success message'),
        ),
        migrations.AlterField(
            model_name='feedbackaction',
            name='label',
            field=models.CharField(blank=True, max_length=200, verbose_name='Button label'),
        ),
        migrations.AlterField(
            model_name='feedbackaction',
            name='label_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Button label'),
        ),
        migrations.AlterField(
            model_name='feedbackaction',
            name='label_kk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Button label'),
        ),
        migrations.AlterField(
            model_name='feedbackaction',
            name='label_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Button label'),
        ),
        migrations.AlterField(
            model_name='feedbackaction',
            name='name_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Name label'),
        ),
        migrations.AlterField(
            model_name='feedbackaction',
            name='phone_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Phone label'),
        ),
        migrations.AlterField(
            model_name='feedbackaction',
            name='submit_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Submit button label'),
        ),
        migrations.AlterField(
            model_name='feedbackaction',
            name='submit_label_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Submit button label'),
        ),
        migrations.AlterField(
            model_name='feedbackaction',
            name='submit_label_kk',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Submit button label'),
        ),
        migrations.AlterField(
            model_name='feedbackaction',
            name='submit_label_ru',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Submit button label'),
        ),
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(blank=True, max_length=500, verbose_name='Page URL')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('locale', models.CharField(blank=True, max_length=10, verbose_name='Locale')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='feedback.feedbackaction')),
            ],
            options={
                'verbose_name': 'Feedback submission',
                'verbose_name_plural': 'Feedback submissions',
                'ordering': ['-created', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='FeedbackRequest',
        ),
    ]
