# Generated by Django 5.2.1 on 2025-09-01 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_kk', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtitle')),
                ('subtitle_kk', models.CharField(blank=True, max_length=300, null=True, verbose_name='Subtitle')),
                ('subtitle_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Subtitle')),
                ('subtitle_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Subtitle')),
                ('author', models.CharField(blank=True, max_length=160, verbose_name='Author')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published at')),
                ('tags_text', models.CharField(blank=True, max_length=300, verbose_name='Tags (comma-separated)')),
                ('image', models.ImageField(blank=True, upload_to='blog/', verbose_name='Image')),
                ('body_md', models.TextField(blank=True, verbose_name='Body (Markdown)')),
                ('body_md_kk', models.TextField(blank=True, null=True, verbose_name='Body (Markdown)')),
                ('body_md_ru', models.TextField(blank=True, null=True, verbose_name='Body (Markdown)')),
                ('body_md_en', models.TextField(blank=True, null=True, verbose_name='Body (Markdown)')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta title')),
                ('meta_title_kk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('meta_description_kk', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('meta_description_ru', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog post',
                'verbose_name_plural': 'Blog posts',
                'ordering': ['-published_at', '-id'],
            },
        ),
    ]
