# Generated by Django 5.2.1 on 2025-09-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='blog', unique=True, verbose_name='Slug')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('title_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta title')),
                ('meta_title_kk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('meta_description_kk', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('meta_description_ru', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog page settings',
                'verbose_name_plural': 'Blog page settings',
            },
        ),
    ]
