# Generated by Django 5.2.1 on 2025-09-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Page title')),
                ('title_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Page title')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Page title')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Page title')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta title')),
                ('meta_title_kk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('meta_description_kk', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('meta_description_ru', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Meta keywords (comma-separated)')),
                ('meta_keywords_kk', models.TextField(blank=True, null=True, verbose_name='Meta keywords (comma-separated)')),
                ('meta_keywords_ru', models.TextField(blank=True, null=True, verbose_name='Meta keywords (comma-separated)')),
                ('meta_keywords_en', models.TextField(blank=True, null=True, verbose_name='Meta keywords (comma-separated)')),
            ],
            options={
                'verbose_name': 'Blog settings',
                'verbose_name_plural': 'Blog settings',
            },
        ),
        migrations.DeleteModel(
            name='BlogIndex',
        ),
    ]
